version: '3'

services:
  front_end_container:
    build:
      context: .
      dockerfile: SustainML.dockerfile
    container_name: front_end_container
    environment:
      - node=orchestrator
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: "host"

  app_requirements_container:
    build:
      context: .
      dockerfile: SustainML.dockerfile
    container_name: app_requirements_container
    environment:
      - node=app_requirements
    network_mode: "host"

  carbon_tracker_container:
    build:
      context: .
      dockerfile: SustainML.dockerfile
    container_name: carbon_tracker_container
    environment:
      - node=carbon_tracker
    network_mode: "host"

  hw_constraints_container:
    build:
      context: .
      dockerfile: SustainML.dockerfile
    container_name: hw_constraints_container
    environment:
      - node=hw_constraints
    network_mode: "host"

  hw_resources_container:
    build:
      context: .
      dockerfile: SustainML.dockerfile
    container_name: hw_resources_container
    environment:
      - node=hw_resources
    network_mode: "host"

  ml_model_container:
    build:
      context: .
      dockerfile: SustainML.dockerfile
    container_name: ml_model_container
    environment:
      - node=ml_model
    network_mode: "host"

  ml_model_metadata_container:
    build:
      context: .
      dockerfile: SustainML.dockerfile
    container_name: ml_model_metadata_container
    environment:
      - node=ml_model_metadata
    network_mode: "host"
