name: 'install_apt_packages'
description: 'Install necessary apt packages'
runs:
  using: "composite"
  steps:
    - id: install_apt_packages
      run: |
        sudo apt update && sudo apt -y install \
          doxygen \
          graphviz \
          imagemagick \
          python3 \
          python3-pip \
          python3-sphinxcontrib.spelling \
          python3-venv \
          software-properties-common \
          wget \
          clang-tidy \
          curl \
          grep
      shell: bash
